name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch: 

jobs:
  CI:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout do repositorio
        uses: actions/checkout@v4.1.2
      - name: autenticacao no Docker
        uses: docker/login-action@v3.1.0
        with: 
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      - name: Construção da imagem docker
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: 
            gusstavota6621/devops4devs-news:latest
            gusstavota6621/devops4devs-news:9
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps: 
      - name: Conectar no Kubernets
        run: echo "COnfiguração do kubeconfig"
      - name: Executar o deploy
        run: echo "kubectl apply"
