name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch: 
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: us-central1 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: my-first-cluster-1    # TODO: update to cluster name
  GKE_ZONE: northamerica-northeast1-c    # TODO: update to cluster zone
  DEPLOYMENT_NAME: gke-test-DevopsNews # TODO: update to deployment name
  REPOSITORY: imagens # TODO: update to Artifact Registry docker repository
  IMAGE: gusstavota6621/devops4devs-news:${{github.run_number}}
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout do repositorio
        uses: actions/checkout@v4.1.2
      - name: autenticacao no Docker
        uses: docker/login-action@v3.1.0
        with: 
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      - name: Construção da imagem docker
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./kube-news/src
          file: ./kube-news/src/Dockerfile
          push: true
          tags: |
            gusstavota6621/devops4devs-news:latest
            gusstavota6621/devops4devs-news:${{github.run_number}}
      # Build the Docker image
     # - name: Build
       # run: |-
          #docker build \
           # --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
            #--build-arg GITHUB_SHA="$GITHUB_SHA" \
            #--build-arg GITHUB_REF="$GITHUB_REF" \
            #.
    # Push the Docker image to Google Artifact Registry
      #- name: Publish
       # run: |-
        #  docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"    
        # ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps: 
      - name: Checkout do repositorio
        uses: actions/checkout@v4.1.2
      - name: configurar autenticacao no gcp
        uses: google-github-actions/auth@v2.1.2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/612478183133/locations/global/workloadIdentityPools/github-actions-backend/providers/github'
          service_account: ${{ secrets.GOOGLE_SA_EMAIL }}
          
      - name: Docker configuration
        run: |-
          echo $GAR_LOCATION
          echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev     
      - name: Set up GKE credentials    
        uses: google-github-actions/get-gke-credentials@v2.1.0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
         # Build the Docker image
      - name: Build
        run: |-
          docker build \
            --tag "us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .
    # Push the Docker image to Google Artifact Registry
      - name: Publish
        run: |-
          docker push "us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"

      - name: Conectar no Kubernets
        run: echo "COnfiguração do kubeconfig"
        
      - name: atualizacao do manifesto
        shell: bash
        run: |
          sed -i "s/{{ACCESS_KEY}}/${{ secrets.GCP_ACCESS_KEY }}"/g ./kube-news/k8s/deploy.yaml
          sed -i "s/{{ACCESS_SECRET}}/${{ secrets.GCP_ACCESS_SECRET }}"/g ./kube-news/k8s/deploy.yaml
      - name: Executar o deploy
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            ./kube-news/k8s/deploy.yaml
          images: |
            $IMAGE
            
