name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch: 

jobs:
  CI:
    runs-on: ubuntu-latest
    steps: 
      - name: Construção da imagem docker
        run: echo "docker build"
      - name: "pubicar a imagem no docker hub"
        run: echo "Docker push"
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps: 
      - name: Conectar no Kubernets
        run: echo "COnfiguração do kubeconfig"
      - name: Executar o deploy
        run: echo "kubectl apply"
